### ISSUE TITLE
2024.5.0 Incompatibility.

### ISSUE THREAD

**Issue by CA1012** [t0stiman/rr_tostilities#2]
With the release of 2024.5.0, the mod no longer functions. I've attached a screenshot of the UMM Log.
![image](https://github.com/user-attachments/assets/4128901b-f83a-4d20-b000-09b016036d9a)

**Comment by WarrenCol** [comment]
Same with Railroader 2024.5.2a
Sure would love to use some of those features.  Like no derailment (Run max speeds through tight turns.  Evil grin)


Log file follows:

Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Railroader/Railroader_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Railroader/MonoBleedingEdge/etc'
[PhysX] Initialized MultithreadedTaskDispatcher with 32 workers.
Initialize engine version: 2022.3.36f1 (95a4219250e5)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Railroader/Railroader_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 4060 Laptop GPU (ID=0x28e0)
    Vendor:   NVIDIA
    VRAM:     7972 MB
    Driver:   31.0.15.4680
Begin MonoManager ReloadAssembly


[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.27.14.0.
[Manager] OS: Microsoft Windows NT 10.0.22631.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2022.3.361.
[Manager] Game: Railroader.
[Manager] IsSupportOnSessionStart: False.
[Manager] IsSupportOnSessionStop: False.
[Manager] Mods path: C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods.
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Railroader/Railroader_Data/MonoBleedingEdge/data-0000014C75BE3310.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Railroader/Railroader_Data/MonoBleedingEdge/data-0000014C75E8E140.dll
[Manager] Injection successful.
- Loaded All Assemblies, in  0.390 seconds
- Finished resetting the current domain, in  0.001 seconds
<RI> Initializing input.
New input system (experimental) initialized
Using Windows.Gaming.Input
<RI> Input initialized.

  ______ _   _ _____     ____  ______   _      ____   _____ 
 |  ____| \ | |  __ \   / __ \|  ____| | |    / __ \ / ____|
 | |__  |  \| | |  | | | |  | | |__    | |   | |  | | |  __ 
 |  __| | . ` | |  | | | |  | |  __|   | |   | |  | | | |_ |
 | |____| |\  | |__| | | |__| | |      | |___| |__| | |__| |
 |______|_| \_|_____/   \____/|_|      |______\____/ \_____|
                                                            

Railloader Injector 1.0.0.0 has been loaded. Further logging will be handled by Railloader+Serilog and will not appear in the Player.log anymore.

Due to Unity's behaviour, it is possible that a few events will appear after this notice, but the majority of the game's log will be in the railloader.log in your game directory.
<RI> Initialized touch support.
[PhysX] Initialized MultithreadedTaskDispatcher with 32 workers.
UnloadTime: 273.787200 ms
[Manager] Starting.
[Manager] Parsing mods.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\A12-440 Tender Trucks\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\AssetLoader\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\better_ui_mod\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\CLB_ASSETS_01\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\DW5ConnellyTweaks\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\DW5SylvaLoop\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\DWFiv3CoalMine\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GN Better Whistles\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GN-A12-440\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GN-F7a\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GN-F7b\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GN-SP Caboose\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GP38Public\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\GP38SoundMod\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\MapEnhancer\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\MemoryLeakFPSfix\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\Multiscreen\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\P3Horn\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\Pass Cars Upgrades V1_3_3\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\passengers_ui_mod\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\Tender swaps\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\tostilities\Info.json'.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Railroader\Mods\Utilities\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[A12-440 Tender Trucks] Version '1.0.0'. Loading.
[A12-440 Tender Trucks] Active.
[A12-440 Tender Trucks] Loading time 0.00 s.
[AssetLoader] Version '1.0.1'. Loading.
[AssetLoader] Active.
[AssetLoader] Loading time 0.01 s.
[better_ui_mod] Version '0.0.4'. Loading.
[better_ui_mod] loaded
[better_ui_mod] hello!
[better_ui_mod] Active.
[better_ui_mod] Loading time 0.04 s.
[CLB_ASSETS_01] Version '1.0.1'. Loading.
[CLB_ASSETS_01] Active.
[CLB_ASSETS_01] Loading time 0.00 s.
[DW5ConnellyTweaks] Version '1.0.0'. Loading.
[DW5ConnellyTweaks] Active.
[DW5ConnellyTweaks] Loading time 0.00 s.
[DW5SylvaLoop] Version '1.2.0'. Loading.
[DW5SylvaLoop] Active.
[DW5SylvaLoop] Loading time 0.00 s.
[DW5CoalMine] Version '1.0.2'. Loading.
[DW5CoalMine] Active.
[DW5CoalMine] Loading time 0.00 s.
[GN Better Whistles] Version '1.0.0'. Loading.
[GN Better Whistles] Active.
[GN Better Whistles] Loading time 0.00 s.
[GN-A12-440] Version '1.0.0'. Loading.
[GN-A12-440] Active.
[GN-A12-440] Loading time 0.00 s.
[GN-F7a] Version '1.0.1'. Loading.
[GN-F7a] Active.
[GN-F7a] Loading time 0.00 s.
[GN-F7b] Version '1.0.1'. Loading.
[GN-F7b] Active.
[GN-F7b] Loading time 0.00 s.
[GN-SP Caboose] Version '1.0.0'. Loading.
[GN-SP Caboose] Active.
[GN-SP Caboose] Loading time 0.00 s.
[GP38Public] Version '1.02'. Loading.
[GP38Public] Active.
[GP38Public] Loading time 0.00 s.
[GP38SoundMod] Version '1.02'. Loading.
[GP38SoundMod] Loading Boombox bundle from C:/Program Files (x86)/Steam/steamapps/common/Railroader/Railroader_Data/StreamingAssets\AssetPacks/Boombox/boomboxbundle
Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Railroader/Railroader_Data/StreamingAssets/AssetPacks/Boombox/boomboxbundle
[GP38SoundMod] Active.
[GP38SoundMod] Loading time 0.01 s.
[MapEnhancer] Version '1.5.2'. Loading.
[MapEnhancer] Active.
[MapEnhancer] Loading time 0.05 s.
[MemoryLeakFPSfix] Version '1.0.1'. Loading.
[MemoryLeakFPSfix] CanvasDecalRenderer.Render not found
[MemoryLeakFPSfix] Active.
[MemoryLeakFPSfix] Loading time 0.02 s.
[Multiscreen] Version '1.5.1.0'. Loading.
[Multiscreen] [13:09:20.102] [Info] Patching...
[Multiscreen] [13:09:20.152] [Info] Patched
[Multiscreen] [13:09:20.152] [Info] Display Count: 1
[Multiscreen] [13:09:20.153] [Info] Less than 2 displays detected, nothing to do...
[Multiscreen] Active.
[Multiscreen] Loading time 0.06 s.
[P3Horn] Version '2.0'. Loading.
[P3Horn] loaded
[P3Horn] hello!
[P3Horn] Active.
[P3Horn] Loading time 0.02 s.
[ParlorCars] Version '1.3.3'. Loading.
[ParlorCars] Active.
[ParlorCars] Loading time 0.00 s.
[passengers_ui_mod] Version '0.0.1'. Loading.
[passengers_ui_mod] loaded
[passengers_ui_mod] hello!
[passengers_ui_mod] Active.
[passengers_ui_mod] Loading time 0.02 s.
[TenderSwaps] Version '1.8.7'. Loading.
[TenderSwaps] Active.
[TenderSwaps] Loading time 0.00 s.
[tostilities] Version '0.0.4'. Loading.
[tostilities] [Exception] Failed to load Tostilities:: HarmonyException - Patching exception in method null
HarmonyLib.HarmonyException: Patching exception in method null ---> System.ArgumentException: Undefined target method for patch method static System.Boolean tostilities.Patches.PlayersManager_NotifyOfNewPlayers_Patch::Prefix(Game.State.PlayersManager& __instance, System.Collections.Generic.Dictionary`2<System.String, Game.Messages.Player> players)
  at HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal, System.Boolean unpatch) [0x00047] in <ba413ca8a8864098887aadc8030b3c3a>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x0006e] in <ba413ca8a8864098887aadc8030b3c3a>:0 
   --- End of inner exception stack trace ---
  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x00154] in <ba413ca8a8864098887aadc8030b3c3a>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x000a0] in <ba413ca8a8864098887aadc8030b3c3a>:0 
  at HarmonyLib.Harmony.<PatchAll>b__10_0 (System.Type type) [0x00007] in <ba413ca8a8864098887aadc8030b3c3a>:0 
  at HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <ba413ca8a8864098887aadc8030b3c3a>:0 
  at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00006] in <ba413ca8a8864098887aadc8030b3c3a>:0 
  at tostilities.Main.Load (UnityModManagerNet.UnityModManager+ModEntry modEntry) [0x000ce] in <dbfe0f689baa4f6eb08986da0f40a186>:0 
[tostilities] Not loaded.
[tostilities] Loading time 0.07 s.
[Utilities] Version '1.2.2'. Loading.
[Utilities] Active.
[Utilities] Loading time 0.92 s.
[Manager] FINISH. SUCCESSFUL LOADED 22/23 MODS.


[Manager] Spawning.
Failed to read data for the AssetBundle 'boomboxbundle'.
[Manager] Checking updates.

**Comment by t0stiman** [comment]
i just updated the mod

**Comment by WarrenCol** [comment]
Thanks.  WOHO.   Got a Berkshire up to 79 mph and a diesel to 66.  Lots of screeching but no damage or derailing (when set to not damage or derail).  <Evil Laugh>.
